[package]
name = "tapo"
version = "0.4.0"
edition = "2021"
license = "MIT"
authors = ["Mihai Dinculescu <mihai.dinculescu@outlook.com>"]
description = "Unofficial Tapo API Client. Works with TP-Link Tapo smart devices. Tested with light bulbs (L510, L530) and plugs (P100, P105, P110, P115)."
keywords = ["IOT", "tapo", "smart-home", "smart-bulb", "smart-plug"]
categories = ["hardware-support", "embedded", "development-tools"]
readme = "README.md"
repository = "https://github.com/mihai-dinculescu/tapo"

[dependencies]
anyhow = "1.0"
base16ct = { version = "0.2", features = ["alloc"] }
base64 = "0.21"
isahc = { version = "1.7", features = ["json", "cookies"] }
lazy_static = "1.4"
log = "0.4"
openssl = "0.10"
serde = { version = "1.0", features = ["derive", "serde_derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["parsing"] }

[dev-dependencies]
pretty_env_logger = "0.4"
tokio = { version = "1.27", features = ["rt-multi-thread", "macros"] }
time = { version = "0.3", features = ["parsing", "macros"] }
