[workspace]
resolver = "2"

members = ["tapo", "tapo-py"]

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4.34", default-features = false }
pyo3 = { version = "0.23" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1.43", default-features = false }
